version: '3.4'

services:
  tiendaservicios.api.autors:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6104:80"

  tiendaservicios.api.libro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80" #Aca se esta ejecutando en el puerto 80 pero lo cambiaremos que a nivel externo se ejecute en el puerto 6105 y anivel interno del container si se va a ejecutar ene puerto 80

